### ISSUE TITLE
Add spells from Strixhaven's supplement to the Spell Point list

### ISSUE THREAD

**Issue by C-allum** [rtotheichie/Avrae-Aliases#106]
This would allow spells like wither and bloom to be cast with spell points.

**Comment by C-allum** [comment]
Added a pull request that includes this and Fizban's spells

**Comment by rtotheichie** [comment]
Thanks for the report! I am not seeing a PR for this.  However, you can create the GVAR yourself and add it following the "homebrew" instructions.
