### ISSUE TITLE
Correct Code for Moongeist Beam

### ISSUE THREAD

**Issue by CatapultMuffins** [rtotheichie/Avrae-Aliases#75]
{"_v": 2, "automation": [{"effects": [{"dc": "{8+proficiencyBonus+max(wisdomMod,dexterityMod)}", "fail": [{"damage": "{damage}+{max(wisdomMod,dexterityMod)} [Ghost]", "overheal": false, "type": "damage"}], "stat": "dex", "success": [{"damage": "({damage}+{max(wisdomMod,dexterityMod)} [Ghost])/2", "overheal": false, "type": "damage"}], "type": "save"}], "meta": [{"dice": "8d12", "hidden": false, "name": "damage", "type": "roll"}], "target": "all", "type": "target"}, {"text": "You emit a sinister ray that explodes out from you in a 100 foot line, 5 feet wide. All creatures caught in the blast must make a DEX save against your Move DC, taking 5d6 + MOVE ghost damage on a failure or half as much on a success. This attack ignores any of the creature's abilities that would affect the user's ability to hit or deal full damage.", "type": "text"}], "name": "Moongeist Beam", "proper": true, "verb": null}

**Comment by rtotheichie** [comment]
Corrected in last code revision . Thanks for the report!
