### ISSUE TITLE
SW5e - !swequip output

### ISSUE THREAD

**Issue by AtinVexien** [rtotheichie/Avrae-Aliases#92]
**Describe the bug**
When using !swequip output <weapon name>, the JSON code created uses ' in all places there should be ", causing a copy-and-paste of the output code to not function with the !attack import function.

**Severity**
Moderate - irrelevant for the baseline weapons, but using output and import is the easiest way to modify weapons for unique features that are applicable to a specific character (changing the attribute used, bonuses from an enhanced item, etc.)

**Screenshots**
![image](https://user-images.githubusercontent.com/85416481/120905592-198fb180-c621-11eb-9ae8-27e5d0399111.png)

**Comment by rtotheichie** [comment]
Fixed. Thanks for the report!
